### ISSUE TITLE
Error - relation "foias_specialperson" does not exist

### ISSUE THREAD

**Issue by rdmurphy** [newsdev/foialawya#9]
I think the migration that renamed `NytEmployee` to `SpecialPerson` was not created. I hit this error when I visited this page: http://localhost:8080/admin/foias/specialperson/

I shelled into the Docker container and ran `makemigrations` and `migrate`, and it cleared it up!

**Comment by rdmurphy** [comment]
(Happy to submit a pull for that if you'd like.)

**Comment by jeremybmerrill** [comment]
Oooh... thank you, good catch. I'll run the makemigration and commit right now.
